#ifndef APPLICATIONCLIENTINTERFACE_EXPORT_H
#define APPLICATIONCLIENTINTERFACE_EXPORT_H
#include <QtCore/qglobal.h>
#if defined(BUILDAPPLICATIONCLIENTINTERFACE)
#define APPLICATION_CLIENT_INTERFACE Q_DECL_EXPORT
#else
#define APPLICATION_CLIENT_INTERFACE Q_DECL_IMPORT
#endif
#endif // APPLICATIONCLIENTINTERFACE_EXPORT_H
